name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run all python test
      id: run-all-python-test
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: ''
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        RUN-ALL-PYTHON-TEST_RESULTS: "${{steps.run-all-python-test.outputs.result}}"
      with:
        runners: run-all-python-test
